StoreApp/Controllers/OrderController.cs
using Entities.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Services.Contracts;

namespace StoreApp.Controllers
{
    public class OrderController : Controller
    {
        private readonly IServiceManager _serviceManager;
        private readonly Cart cart;

        public OrderController(IServiceManager serviceManager, Cart cart)
        {
            _serviceManager = serviceManager;
            this.cart = cart;
        }

        [Authorize]
        public ViewResult Checkout() => View(new Order());

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Checkout([FromForm] Order order)
        {
            if (cart.CartLines.Count() == 0)
                ModelState.AddModelError("", "Sorry, your cart is empty");

            if (ModelState.IsValid)
            {
                order.CartLines = cart.CartLines.ToArray();
                _serviceManager.OrderService.SaveOrder(order);
                cart.Clear();
                return RedirectToPage("/complete", new { OrderId = order.OrderId });
            }
            else
            {
                return View();
            }
        }
    }
}

StoreApp/Pages/Cart.cshtml.cs
using Entities.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Services.Contracts;
using StoreApp.Infrastructure.Extensions;

namespace StoreApp.Pages
{
    public class CartModel : PageModel
    {
        private readonly IServiceManager _serviceManager;
        public Cart _cart { get; set; }
        public string ReturnUrl { get; set; } = "/";

        public CartModel(IServiceManager serviceManager, Cart cartService)
        {
            _serviceManager = serviceManager;
            _cart = cartService;
        }

        public void OnGet(int productId, string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
            //_cart = HttpContext.Session.GetJson<Cart>("cart");
        }

        public IActionResult OnPost(int productId, string _returnUrl)
        {
            Product? product = _serviceManager.ProductService.GetOneProduct(productId, false);

            if (product is not null)
            {
                //_cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();
                _cart.AddItem(product, 1);
                //HttpContext.Session.SetJson<Cart>("cart", _cart);
            }

            return RedirectToPage(new { returnUrl = _returnUrl });
        }

        public IActionResult OnPostRemove(int productId, string returnUrl)
        {
            //_cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();
            _cart.RemoveCartLine(_cart.CartLines.First(cl => cl.CartLineProduct.ProductId.Equals(productId)).CartLineProduct);
            //HttpContext.Session.SetJson<Cart>("cart", _cart);
            return Page();
        }
    }
}

StoreApp/Pages/Demo.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace StoreApp.Pages
{
    public class DemoModel : PageModel
    {
        public String? FullName => HttpContext.Session.GetString("name");
        public void OnGet()
        {
        }

        public void OnPost(string name)
        {
            HttpContext.Session.SetString("name", name);
        }
    }
}

StoreApp/Pages/Cart.cshtml
@page "/cart"
@model CartModel

<div>
    <div class="display-6 text-center my-3">
        CART
    </div>
    <table>
        <thead>
            <tr>
                <th>Image</th>
                <th>Product</th>
                <th>Quantity</th>
                <th>Price</th>
                <th>Subtotal</th>
                <th>Operations</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var cl in Model._cart?.CartLines ?? Enumerable.Empty<CartLine>())
            {
                <tr>
                    <td>
                        <img src="@cl.CartLineProduct.ProductImageUrl" width="50" class="rounded shadow" />
                    </td>
                    <td>@cl.CartLineProduct.ProductName</td>
                    <td>@cl.Quantity</td>
                    <td>@cl.CartLineProduct.ProductPrice.ToString("c")</td>
                    <td>@((cl.CartLineProduct.ProductPrice * cl.Quantity).ToString("c2"))</td>
                    <td>
                        <form method="post" asp-page-handler="Remove">
                            <input type="hidden" name="productId" value="@cl.CartLineProduct.ProductId" />
                            <input type="hidden" name="returnUrl" value="@Model.ReturnUrl" />

                            <button type="submit" class="btn btn-sm btn-danger">
                                <i class="fa fa-trash"></i>
                                Remove
                            </button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <td class="text-right" colspan="4">
                    Total Price:
                </td>
                <td class="text-right text-info">
                    @Model._cart?.ComputeTotalValue().ToString("c2")
                </td>
            </tr>
        </tfoot>
    </table>
    <div class="my-3 text-center">
        <div class="btn btn-group">
            <a class="btn btn-primary" href="@Model?.ReturnUrl">
                Continue Shopping
            </a>
            <a class="btn btn-primary mx-3" asp-action="Checkout" asp-controller="Order">
                Checkout
            </a>
        </div>
    </div>
</div>

StoreApp/Pages/Complete.cshtml
@page "/complete"

<div class="text-center">
    <h6 class="display-6">THANKS</h6>
    <p>Thanks for placing order #@OrderId</p>
    <p>We'll ship your orders as soon as possible</p>
    <a class="btn btn-primary" asp-action="Index" asp-controller="Home">Return to Home</a>
</div>

@functions {
    [BindProperty(SupportsGet = true)]
    public String? OrderId { get; set; }
}

StoreApp/Pages/Contact.cshtml
@page "/getintouch"

<div class="text-center my-5 ">
    <div class="display-6 border-bottom">Contact</div>
    <div class="lead mt-5">
        <i class="fa fa-phone bg-secondary text-white p-3  rounded-5 my-3"></i>
        <p>
            ALO 120 BTK Akademi bilgi ve destek hattı
        </p>
        <i class="fa-solid fa-address-book bg-secondary text-white p-3  rounded-5 my-3"></i>
        <p>
            Bilgi Teknolojileri ve İletişim Kurumu Eskişehir Yolu 10.Km
            No: 276 Posta Kodu: 06530 Çankaya/Ankara
        </p>

        <i class="fa-solid fa-envelope bg-secondary text-white p-3  rounded-5 my-3"></i>
        <p>
            destek@btkakademi.gov.tr
        </p>
    </div>
</div>

StoreApp/Pages/Demo.cshtml
@page "/demo"
@model StoreApp.Pages.DemoModel


<div class="text-center">
    <div class="display-6 my-3">
        Merhaba <span style="font-family: 'Times New Roman', Times, serif;">@Model.FullName</span>
    </div>
    <form method="post" asp-page="/demo">
        <div class="form-group">
            <input placeholder="Enter your nickname" name="name" class="form-controller my-3" />
            <input type="submit" class="btn btn-primary my-3" />
        </div>
    </form>
</div>