StoreApp/Components/CartSummaryViewComponent.cs
using Entities.Models;
using Microsoft.AspNetCore.Mvc;

namespace StoreApp.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private readonly Cart _cart;

        public CartSummaryViewComponent(Cart cartService)
        {
            _cart = cartService;
        }

        public string Invoke()
        {
            return _cart.CartLines.Count().ToString();
        }
    }
}

StoreApp/Components/ProductSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Services.Contracts;

namespace StoreApp.Components
{
    public class ProductSummaryViewComponent : ViewComponent
    {
        private readonly IServiceManager _serviceManager;

        public ProductSummaryViewComponent(IServiceManager serviceManager)
        {
            _serviceManager = serviceManager;
        }

        public string Invoke()
        {
            return _serviceManager.ProductService.GetAllProducts(false).Count().ToString();
        }
    }
}

StoreApp/Controllers/CategoryController.cs
using Entities.Models;
using Microsoft.AspNetCore.Mvc;
using Repositories.Contracts;

namespace StoreApp.Controllers
{
    public class CategoryController : Controller
    {
        private IRepositoryManager _repositoryManager;

        public CategoryController(IRepositoryManager repositoryManager)
        {
            _repositoryManager = repositoryManager;
        }

        public IActionResult Index()
        {
            var model = _repositoryManager.Category.FindAll(false);
            return View(model);
        } 
    }
}

StoreApp/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Entities.Models;
using Repositories;
using Repositories.Contracts;
using Services.Contracts;
using Entities.RequestParameters;
using StoreApp.Models;

namespace StoreApp.Controllers
{
    public class ProductController : Controller
    {
        private readonly IServiceManager _serviceManager;

        public ProductController(IServiceManager serviceManager)
        {
            _serviceManager = serviceManager;
        }

        public IActionResult Index(ProductRequestParameters p)
        {
            var products = _serviceManager.ProductService.GetAllProductsWithDetails(p);
            var pagination = new Pagination()
            {
                ItemsPerPage = p.PageSize,
                CurrentPage = p.PageNumber,
                TotalItems = _serviceManager.ProductService.GetAllProducts(false).Count()
            };

            return View(new ProductListViewModel()
            {
                Products = products,
                Pagination = pagination
            });
        }

        public IActionResult Get([FromRoute(Name ="Id")] int Id)
        {
            // Product product = _repositoryManager.Product.First(p => p.ProductId.Equals(Id));
            var model = _serviceManager.ProductService.GetOneProduct(Id, false);
            ViewData["title"] = $" - {model?.ProductName}";
            return View(model);
        }
    }
}

StoreApp/Views/Shared/_Footer.cshtml
<div class="bg-light border-top p-3">
    <div class="container">
        <div class="row">
            <div class="col-md-2">
                <div class="lead text-center ">
                    <i class="fa-solid fa-store text-secondary display-6"></i>
                    <br />
                    <bold>BTK</bold> Akademi
                </div>
                <div class="text-muted text-center">
                    Store App
                </div>
            </div>
            <div class="col-md-8">
                <div class="text-center text-muted my-3">
                    &copy; 2023 <br />BTK Akademi ASP.NET Core MVC Eğitimi
                </div>

                <div class="text-center">
                    <div class="btn-group">
                        <a class="btn btn-secondary">
                            <i class="fa-brands fa-facebook"></i>
                        </a>
                        <a class="btn btn-secondary">
                            <i class="fa-brands fa-twitter"></i>
                        </a>
                        <a class="btn btn-secondary">
                            <i class="fa-brands fa-linkedin"></i>
                        </a>
                        <a class="btn btn-secondary">
                            <i class="fa-brands fa-youtube"></i>
                        </a>
                        <a class="btn btn-secondary">
                            <i class="fa-brands fa-instagram"></i>
                        </a>
                    </div>
                </div>

            </div>
            <div class="col-md-2">
                <div products="" number="6"></div>
            </div>
        </div>
    </div>
</div>

StoreApp/Views/Shared/_Layout.cshtml
<html>
    <head>
        <title>StoreApp @ViewData["title"]</title>
        <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
    </head>
    <body>
        <header>
            <partial name="_Navbar" />
            @RenderSection("Header", false)
        </header>

        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

        <footer>
            @RenderSection("Footer", false)
            <partial name="_Footer" />
        </footer>

        <script src="~/lib/jquery/jquery.min.js"></script>
        <script src="~/lib/font-awesome/js/all.min.js"></script>
        <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js"></script>

        @await RenderSectionAsync("Scripts", false)
    </body>
</html>

StoreApp/Views/Shared/_LoginMenu.cshtml
@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
    <li class="nav-item">
        <a class="nav-link" aria-current="page" target="_blank" asp-area="Admin" asp-controller="Dashboard" asp-action="Index">ADMIN</a>
    </li>
}

@if (User.Identity.IsAuthenticated)
{
    <li class="nav-item">
        <a class="nav-link"
           aria-current="page"
           asp-area=""
           asp-controller="Account"
           asp-route-ReturnUrl="@Context.Request.PathAndQuery()"
           asp-action="Logout">Logout</a>
    </li>
}
else
{
    <li class="nav-item">
        <a class="nav-link"
           aria-current="page"
           asp-area=""
           asp-controller="Account"
           asp-route-ReturnUrl="@Context.Request.PathAndQuery()"
           asp-action="Login">Login</a>
    </li>
}

StoreApp/Views/Shared/_Navbar.cshtml
<nav class="navbar bg-primary border-bottom navbar-expand-lg bg-body-tertiary">
    <div class="container">
        <i class="fa-solid fa-store fa-2x text-primary"></i>
        <a class="navbar-brand" href="/">Store App</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup">
            <span class="navbar-toggle-icon"></span>
        </button>

        <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between" id="navbarNavAltMarkup">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" asp-controller="Product" asp-action="Index">
                        Products
                        (@await Component.InvokeAsync("ProductSummary"))
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" asp-controller="Category" asp-action="Index">Categories</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" asp-page="/Contact">Contact</a>
                </li>
            </ul>

            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" target="_blank" asp-area="" asp-page="/Cart">
                        CART (@await Component.InvokeAsync("CartSummary"))
                    </a>
                </li>
                <partial name="_LoginMenu" />
            </ul>
        </div>
    </div>
</nav>

StoreApp/Views/Shared/_Notification.cshtml
@if (TempData["info"] is not null)
{
    <div class="alert alert-info my-5" role="alert">
        @TempData["info"]
    </div>
}

@if (TempData["success"] is not null)
{
    <div class="alert alert-success my-5" role="alert">
        @TempData["success"]
    </div>
}

@if (TempData["danger"] is not null)
{
    <div class="alert alert-danger my-5" role="alert">
        @TempData["danger"]
    </div>
}

StoreApp/Views/Shared/_ProductCard.cshtml
@model Product

@* <div>
    <h2>@Model.ProductName</h2>
    <p>@Model.ProductPrice.ToString("c")</p>
    <p>
        <a class="btn btn-primary" asp-action="Get" asp-route-id="@Model.ProductId">
            <i class="fa-solid fa-arrow-right"></i>    
            Get Details
        </a>
    </p>
    <hr />
</div> *@

<div class="col-sm-12 col-md-5 my-2">
    <div class="card" style="width: 18rem;">
        <img src="@Model?.ProductImageUrl" class="card-img-top" alt="..." />
        <div class="card-body">
            <h5 class="card-title">@Model?.ProductName</h5>
            <div class="card-text">

                <div class="text-danger text-center lead p-2 rounded-2">
                    @Model?.ProductPrice.ToString("C2")

                </div>

            </div>
            <p class="card-text"></p>
            <div class="btn btn-group">
                <form method="post" asp-page="/cart" id="@Model?.ProductId">
                    <input type="hidden" asp-for="ProductId"/>
                    <input type="hidden" name="_returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()"/>
                    <button class="btn btn-primary" type="submit">
                        <i class="fa fa-cart-plus"></i>
                    </button>
                </form>

                <a asp-controller="Product" asp-action="Get" asp-route-id="@Model?.ProductId" class="btn btn-primary">
                    <i class="fa-solid fa-arrow-right"></i>
                    Get Details
                </a>
            </div>
        </div>
    </div>
</div>